language: php
notifications:
  on_success: never
  on_failure: change
  slack:
    secure: rs6hDLN8tNCdv8DuBSM47S8Q8r1thSxxRiTN0HaWdracPQkHZIyshW1pxtmvfKdUBI7lGtYGkGGSy24GN+5jLmCRH+p17hKq3zfTyCkiKNgTf//9SXh46YyTsxr9rU20JJt/fyjW1pnF5bcLCjWJeFWMC8fe0m0dHTx7QZHXRqY=
matrix:
  include:
    - php: 5.5.9
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=0
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
